steps:
# Pull the existing image
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker pull gcr.io/becn-sandbox/tomcat:latest || exit 0
      timeout: 660s
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/becn-sandbox/tomcat', '--cache-from', 'gcr.io/becn-sandbox/tomcat', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/becn-sandbox/tomcat"]
# Deploy an image from Container Registry to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['beta', 'run', 'deploy', 'tomcat', '--image', 'gcr.io/becn-sandbox/tomcat:latest', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
 - 'gcr.io/becn-sandbox/tomcat'


